### PR TITLE
Fix detetion for Mocha and Jest

### PR DESCRIPTION
**Pull request by codeinabox**
Arises from #213

### CODE REVIEW

**Comment by janko-m** [comment]
@codeinabox Can you explain the reasoning behind checking for `filereadable('node_modules/.bin/<runner>')`?

**Comment by codeinabox** [comment]
@Akhetopnu could you try switching to this branch and let me know if it fixes your issue.

**Comment by codeinabox** [comment]
@janko-m that was how the existing logic worked but given that would only be true if it's in package.json then it's probably redundant right?

**Comment by janko-m** [comment]
@codeinabox Yes, I think we can remove it, and have the JavaScript runners match only when the corresponding testing framework is listed in `package.json` (the `test#javascript#has_package` condition).

**Comment by janko-m** [comment]
@codeinabox Thanks! I also added https://github.com/janko-m/vim-test/commit/0877dfcace9f77f2bb5d67a21a2f510cfe1e2bd0 which applies that change for other JS test runners as well.

**Pull request merged**
