### PR TITLE
Add nose2 support

### PR DESCRIPTION
**Pull request by furgerf**
I've tried adding nose2 as a new python test runner, based on the nose runner (relates to #138). I've successfully tested `TestFile`, `TestLast`, `TestSuite`, and `TestVisit` but I couldn't get `TestNearest` to work:

Nose2 seems to want indices to run individual tests ([nose2 docs](http://nose2.readthedocs.io/en/latest/usage.html#specifying-tests-to-run)) but what I'm passing is the name of the test function.

Please see this merely as a suggestion - I haven't written any vimscript (besides modifying the odd copied function in my vimrc) before and am certainly no python/nose2 expert... feel free to do with that as you please :)

### CODE REVIEW

**Comment by janko-m** [comment]
> Nose2 seems to want indices to run individual tests

Wow, that's a first 😃. Test.vim is already doing parsing of test files for some runners, I think it shouldn't be difficult to translate tests into indices. I will work on getting that done.

Thanks for the PR! And congratulations on your first VimScript 🎉

**Comment by furgerf** [comment]
> Test.vim is already doing parsing of test files for some runners, I think it shouldn't be difficult to translate tests into indices.

I thought so too but that's a bit too involved for me for the moment :wink: 

Glad to be able to help and thank you for your work!

**Comment by codeinabox** [comment]
@furgerf are able to rebase this? I can give help if needed

**Comment by furgerf** [comment]
@codeinabox I tried that GitHub thing to rebase, please tell me if that didn't work and I'll do it the old-fashioned way :)

**Comment by codeinabox** [comment]
Rebase looks all fine to me. Is it possible you could add a spec for Nose2 support to demonstrate how it should behave.

**Comment by furgerf** [comment]
Thanks for the heads-up. I copied and adapted the nose spec, looks like TestNearest hasn't been working (I wasn't using that).
Now it works both for a sample runs of TestNearest and on Travis (I don't have Ruby set up to run the tests locally).

**Comment by codeinabox** [comment]
Great thanks for this. Looks good so far. Can you please update the README and doc/test.txt and then it should be ready for merge.

**Comment by furgerf** [comment]
No problem, happy to help - and to close this nearly one-year-old PR :smile:

**Pull request merged**
