### PR TITLE
Let test be in front or at the end.

### PR DESCRIPTION
**Pull request by lyz-code**
As stated [here](https://pytest.readthedocs.io/en/reorganize-docs/new-docs/user/naming_conventions.html).

Taken as reference [the nose modification](https://github.com/janko-m/vim-test/pull/32/files)

### CODE REVIEW

**Comment by codeinabox** [comment]
Thank you for the PR! Could you please update the spec and fixture located in the `spec` folder

**Comment by lyz-code** [comment]
Could you please tell me what to update in the spec and fixture?

I don't see anything that needs changing

**Comment by codeinabox** [comment]
Sorry I meant to say could you please check the directory and file name structure for the nose fixtures are representative of the naming convention if they aren't already. Aside from that LGTM 👍

**Comment by lyz-code** [comment]
If I understood correctly what you are saying, yes, pytest naming convention is compatible with the nose one. As stated on the link of the description, what Pytest says is that the filenames should be `test_filename.py` or `filename_test.py`.

I don't know if that answers your statement :S

**Pull request merged**
